#!/bin/bash
export
set -ex

echo "configuring Pitometer CLI with $DYNATRACE_APITOKEN and $DYNATRACE_BASEURL"

export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
export CURRENT_APP_COLOR=$(cat ./current-app-info/current-app.txt)

eval perfspec=$perfspec

echo "Validating load test results via Pitometer perfspec: $perfspec"

# container contains bash 4.4 so we'll use bash built-ins for start/end timestamps
CURRENT_TIME=$(printf "%(%s)T")
#setting to validate over last 5 minutes
START_TIME=$(printf "$(( $(printf "%(%s)T") - 60 * 60 ))")

echo $PWD
ls -la ./$APP_REPO
ls -la ./$APP_REPO/$perfspec

npm start --prefix /usr/src/app $START_TIME $CURRENT_TIME $PWD/$APP_REPO/$perfspec 
#| tail -n +5 > pitometer_output.json
# jq '.' pitometer_output.json
# result="$(jq -r '.result' pitometer_output.json)"
# if [ "$result" = "fail" ]; then
#   echo "This build has failed based on pitometer evaluation"
#   exit 1
# else
#   echo "This build has passed pitometer evaluation"
#   exit 0
# fi

