---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mvilliger/pitometer-cli
    tag: "0.1.4"

inputs:
- name: music-repo
- name: current-app-info
  optional: true

run:
  path: ./music-repo/ci/tasks/validate-via-pitometer

params:
  perfspec: springmusic-perfspec-stage.json
  DYNATRACE_APITOKEN: ((apitoken))
  DYNATRACE_BASEURL: ((tenanthost))
  APP_REPO: music-repo