---
applications:
- name: APPNAME
  memory: 1G
  instances: 2
  buildpacks: 
    - java_buildpack_offline
  env:
    DT_NODE_ID: APPNAME
    DT_CUSTOM_PROP: DEPLOYMENT_GRP_NME=SPRING-MUSIC-DTGRP DEPLOYMENT_COLOR=SPRING-MUSIC-APPCOLOR
    DEPLOYMENT_GRP_NME: SPRING-MUSIC-DTGRP
    DELAY: 0
    incrementthistoforcenewrelease: 6
